name: Publish

on: [push]
# on:
#   push:
#     branches:
#       - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          TAG="docker.pkg.github.com/miyucy/rbnd/rbnd:$(date -u '+%Y%m%d%H%M%S')"
          docker build -t minid:latest -f Dockerfile.minid .
          cat Dockerfile \
            | docker run -i --rm minid:latest minid -f - \
            | docker build --build-arg APT_MIRROR=US --tag "${TAG}" -f - .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username "${GITHUB_ACTOR}" docker.pkg.github.com
          docker push "${TAG}"
